# For some reasone you need a version here
version: "3.0"
services:
  pgdatabase:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./2_docker_SQL/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  docker_ingest:
    build: ./docker_ingest
    command:
      - "--user=root"
      - "--password=root"
      - "--host=pgdatabase"
      - "--port=5432"
      - "--db=ny_taxi"
      - "--table_name=yellow_taxi_data"
      - "--url=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet"

# docker_ingest:
#docker run -it --network=pg-network ingest:tagger         
#        --user=root\
#        --password=root\
#        --host=postgresql\
#        --port=5432\
#        --db=ny_taxi\
#       --table_name=yellow_taxi_data\
#        --url=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet

